struct Plant {
    name: &'static str,
    seed: u32,
}

fn main() {
    let plants = vec![
        Plant { name: "Crimson Bloom", seed: 12345 },
        Plant { name: "Azure Fern", seed: 54321 },
        Plant { name: "Golden Pine", seed: 98765 },
        Plant { name: "Shadow Root", seed: 13579 },
        Plant { name: "Silver Birch", seed: 24680 },
        Plant { name: "Whispering Willow", seed: 11223 },
        Plant { name: "Sunpetal", seed: 33445 },
        Plant { name: "Moonpetal", seed: 55667 },
        Plant { name: "Starflower", seed: 77889 },
        Plant { name: "Dragon's Breath", seed: 99001 },
        Plant { name: "Ghost Orchid", seed: 10111 },
        Plant { name: "Glimmering Moss", seed: 21212 },
        Plant { name: "Ruby Thorn", seed: 32323 },
        Plant { name: "Sapphire Vine", seed: 43434 },
        Plant { name: "Emerald Ivy", seed: 54545 },
        Plant { name: "Obsidian Rose", seed: 65656 },
        Plant { name: "Opal Cactus", seed: 76767 },
        Plant { name: "Jade Bamboo", seed: 87878 },
        Plant { name: "Topaz Tulip", seed: 98989 },
        Plant { name: "Amethyst Lily", seed: 10101 },
        Plant { name: "Garnet Poppy", seed: 20202 },
        Plant { name: "Diamond Daisy", seed: 30303 },
        Plant { name: "Pearl Blossom", seed: 40404 },
        Plant { name: "Coral Bell", seed: 50505 },
        Plant { name: "Quartz Crystal", seed: 60606 },
        Plant { name: "Turquoise Iris", seed: 70707 },
        Plant { name: "Lapis Lazuli Lupin", seed: 80808 },
        Plant { name: "Malachite Marigold", seed: 90909 },
        Plant { name: "Sunstone Sunflower", seed: 11111 },
        Plant { name: "Moonstone Morning Glory", seed: 22222 },
        Plant { name: "Bloodstone Bellflower", seed: 33333 },
        Plant { name: "Tiger's Eye Thistle", seed: 44444 },
        Plant { name: "Hawk's Eye Heather", seed: 55555 },
        Plant { name: "Cat's Eye Clover", seed: 66666 },
        Plant { name: "Serpentine Snapdragon", seed: 77777 },
        Plant { name: "Agate Aloe", seed: 88888 },
        Plant { name: "Jasper Jasmine", seed: 99999 },
        Plant { name: "Onyx Orchid", seed: 10000 },
        Plant { name: "Carnelian Crocus", seed: 20000 },
        Plant { name: "Sodalite Snowdrop", seed: 30000 },
        Plant { name: "Rhodonite Rhododendron", seed: 40000 },
        Plant { name: "Kyanite Kohlrabi", seed: 50000 },
        Plant { name: "Fluorite Foxglove", seed: 60000 },
        Plant { name: "Aventurine Anemone", seed: 70000 },
        Plant { name: "Amazonite Aster", seed: 80000 },
        Plant { name: "Labradorite Lavender", seed: 90000 },
        Plant { name: "Peridot Petunia", seed: 12121 },
        Plant { name: "Spinel Zinnia", seed: 23232 },
        Plant { name: "Zircon Geranium", seed: 34343 },
        Plant { name: "Tanzanite Dahlia", seed: 45454 },
        Plant { name: "Alexandrite Azalea", seed: 56565 },
        Plant { name: "Morganite Magnolia", seed: 67676 },
        Plant { name: "Heliodor Hibiscus", seed: 78787 },
        Plant { name: "Aquamarine Buttercup", seed: 89898 },
        Plant { name: "Goshenite Gladiolus", seed: 10112 },
        Plant { name: "Bixbite Begonia", seed: 21223 },
        Plant { name: "Fire Opal Freesia", seed: 32334 },
        Plant { name: "Black Opal Oleander", seed: 43445 },
        Plant { name: "Boulder Opal Bluebell", seed: 54556 },
        Plant { name: "Matrix Opal Monkshood", seed: 65667 },
        Plant { name: "Andamooka Opal Aconite", seed: 76778 },
        Plant { name: "Lightning Ridge Opal Larkspur", seed: 87889 },
        Plant { name: "Welsh Opal Wolfsbane", seed: 98990 },
        Plant { name: "Honduran Opal Hollyhock", seed: 10102 },
        Plant { name: "Peruvian Opal Peony", seed: 20203 },
        Plant { name: "Ethiopian Opal Elderflower", seed: 30304 },
        Plant { name: "Mexican Fire Opal Mimosa", seed: 40405 },
        Plant { name: "Brazilian Opal Bougainvillea", seed: 50506 },
        Plant { name: "Slovakian Opal Sweet Pea", seed: 60607 },
        Plant { name: "Tanzanian Opal Tansy", seed: 70708 },
        Plant { name: "Indonesian Opal Impatiens", seed: 80809 },
        Plant { name: "Australian Opal Allium", seed: 90910 },
        Plant { name: "Dragon's Eye", seed: 11112 },
        Plant { name: "Phoenix Feather", seed: 22223 },
        Plant { name: "Griffin's Claw", seed: 33334 },
        Plant { name: "Unicorn's Horn", seed: 44445 },
        Plant { name: "Mermaid's Scale", seed: 55556 },
        Plant { name: "Fairy's Wing", seed: 66667 },
        Plant { name: "Pixie Dust", seed: 77778 },
        Plant { name: "Goblin's Gold", seed: 88889 },
        Plant { name: "Troll's Treasure", seed: 99990 },
        Plant { name: "Dwarf's Delight", seed: 10001 },
        Plant { name: "Elf's Elegance", seed: 20002 },
        Plant { name: "Giant's Growth", seed: 30003 },
        Plant { name: "Nymph's Nectar", seed: 40004 },
        Plant { name: "Satyr's Song", seed: 50005 },
        Plant { name: "Centaur's Courage", seed: 60006 },
        Plant { name: "Minotaur's Maze", seed: 70007 },
        Plant { name: "Hydra's Head", seed: 80008 },
        Plant { name: "Siren's Call", seed: 90009 },
        Plant { name: "Harpy's Feather", seed: 12321 },
        Plant { name: "Chimera's Charm", seed: 23432 },
        Plant { name: "Kraken's Ink", seed: 34543 },
        Plant { name: "Leviathan's Lullaby", seed: 45654 },
        Plant { name: "Behemoth's Blessing", seed: 56765 },
        Plant { name: "Ziz's Zephyr", seed: 67876 },
        Plant { name: "Roc's Roar", seed: 78987 },
        Plant { name: "Thunderbird's Cry", seed: 89098 },
        Plant { name: "Quetzalcoatl's Crest", seed: 90109 },
        Plant { name: "Fenrir's Fang", seed: 10210 },
        Plant { name: "Jormungandr's Coil", seed: 21321 },
        Plant { name: "Sleipnir's Stride", seed: 32432 },
        Plant { name: "Huginn's Thought", seed: 43543 },
        Plant { name: "Muninn's Memory", seed: 54654 },
        Plant { name: "Gungnir's Point", seed: 65765 },
        Plant { name: "Mjolnir's Might", seed: 76876 },
        Plant { name: "Bifrost's Bridge", seed: 87987 },
        Plant { name: "Yggdrasil's Root", seed: 98098 },
        Plant { name: "Asgard's Pride", seed: 10113 },
        Plant { name: "Midgard's Serpent", seed: 21224 },
        Plant { name: "Jotunheim's Jotun", seed: 32335 },
        Plant { name: "Vanaheim's Vanir", seed: 43446 },
        Plant { name: "Alfheim's Elf", seed: 54557 },
        Plant { name: "Svartalfheim's Dwarf", seed: 65668 },
        Plant { name: "Muspelheim's Fire", seed: 76779 },
        Plant { name: "Niflheim's Ice", seed: 87880 },
        Plant { name: "Hel's Hand", seed: 98991 },
        Plant { name: "Ragnarok's Ruin", seed: 10103 },
        Plant { name: "Valhalla's Valor", seed: 20204 },
        Plant { name: "Einherjar's Echo", seed: 30305 },
        Plant { name: "Valkyrie's Voice", seed: 40406 },
        Plant { name: "Norn's Thread", seed: 50507 },
        Plant { name: "Fates' Decree", seed: 60608 },
        Plant { name: "Chaos's Bloom", seed: 70709 },
        Plant { name: "Order's Orchid", seed: 80810 },
        Plant { name: "Light's Lily", seed: 90911 },
        Plant { name: "Dark's Daisy", seed: 11113 },
        Plant { name: "Sun's Sunflower", seed: 22224 },
        Plant { name: "Moon's Morning Glory", seed: 33335 },
        Plant { name: "Star's Snapdragon", seed: 44446 },
        Plant { name: "Sky's Snowdrop", seed: 55557 },
        Plant { name: "Earth's Elderflower", seed: 66668 },
        Plant { name: "Sea's Sweet Pea", seed: 77779 },
        Plant { name: "Fire's Foxglove", seed: 88880 },
        Plant { name: "Wind's Wolfsbane", seed: 99991 },
        Plant { name: "Storm's Snapdragon", seed: 10002 },
        Plant { name: "Ice's Iris", seed: 20003 },
        Plant { name: "Stone's Snapdragon", seed: 30004 },
        Plant { name: "Wood's Wolfsbane", seed: 40005 },
        Plant { name: "Metal's Marigold", seed: 50006 },
        Plant { name: "Void's Violet", seed: 60007 },
        Plant { name: "Aether's Azalea", seed: 70008 },
        Plant { name: "Nether's Nettle", seed: 80009 },
        Plant { name: "Dream's Dahlia", seed: 90010 },
        Plant { name: "Nightmare's Nightshade", seed: 12322 },
        Plant { name: "Memory's Mimosa", seed: 23433 },
        Plant { name: "Thought's Thistle", seed: 34544 },
        Plant { name: "Emotion's Elderflower", seed: 45655 },
        Plant { name: "Soul's Sunflower", seed: 56766 },
        Plant { name: "Spirit's Snapdragon", seed: 67877 },
        Plant { name: "Heart's Hollyhock", seed: 78988 },
        Plant { name: "Mind's Monkshood", seed: 89099 },
        Plant { name: "Body's Bluebell", seed: 90110 },
        Plant { name: "Life's Lily", seed: 10211 },
        Plant { name: "Death's Daisy", seed: 21322 },
        Plant { name: "Time's Thyme", seed: 32433 },
        Plant { name: "Space's Snapdragon", seed: 43544 },
        Plant { name: "Gravity's Gladiolus", seed: 54655 },
        Plant { name: "Energy's Elderflower", seed: 65766 },
        Plant { name: "Matter's Marigold", seed: 76877 },
        Plant { name: "Antimatter's Anemone", seed: 87988 },
        Plant { name: "Quantum's Quince", seed: 98099 },
        Plant { name: "Singularity's Snapdragon", seed: 10114 },
        Plant { name: "Event Horizon's Elderflower", seed: 21225 },
        Plant { name: "Nebula's Nettle", seed: 32336 },
        Plant { name: "Galaxy's Gladiolus", seed: 43447 },
        Plant { name: "Universe's Uva-ursi", seed: 54558 },
        Plant { name: "Multiverse's Monkshood", seed: 65669 },
        Plant { name: "Dimension's Dahlia", seed: 76780 },
        Plant { name: "Reality's Rhododendron", seed: 87881 },
        Plant { name: "Illusion's Iris", seed: 98992 },
        Plant { name: "Truth's Tulip", seed: 10104 },
        Plant { name: "Lie's Lily", seed: 20205 },
        Plant { name: "Hope's Hollyhock", seed: 30306 },
        Plant { name: "Despair's Daisy", seed: 40407 },
        Plant { name: "Joy's Jasmine", seed: 50508 },
        Plant { name: "Sorrow's Snapdragon", seed: 60609 },
        Plant { name: "Love's Lavender", seed: 70710 },
        Plant { name: "Hate's Heather", seed: 80811 },
        Plant { name: "Peace's Peony", seed: 90912 },
        Plant { name: "War's Wolfsbane", seed: 11114 },
        Plant { name: "Wisdom's Wisteria", seed: 22225 },
        Plant { name: "Folly's Foxglove", seed: 33336 },
        Plant { name: "Knowledge's Kohlrabi", seed: 44447 },
        Plant { name: "Ignorance's Iris", seed: 55558 },
        Plant { name: "Power's Poppy", seed: 66669 },
        Plant { name: "Weakness's Wisteria", seed: 77780 },
        Plant { name: "Courage's Crocus", seed: 88881 },
        Plant { name: "Fear's Foxglove", seed: 99992 },
        Plant { name: "Virtue's Violet", seed: 10003 },
        Plant { name: "Sin's Snapdragon", seed: 20004 },
        Plant { name: "Faith's Freesia", seed: 30005 },
        Plant { name: "Doubt's Dahlia", seed: 40006 },
        Plant { name: "Destiny's Daisy", seed: 50007 },
        Plant { name: "Freedom's Foxglove", seed: 60008 },
    ];

    for plant in plants {
        println!("Name: {}, Seed: {}", plant.name, plant.seed);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_plant_list_not_empty() {
        let plants = vec![
            Plant { name: "Crimson Bloom", seed: 12345 },
            Plant { name: "Azure Fern", seed: 54321 },
            Plant { name: "Golden Pine", seed: 98765 },
            Plant { name: "Shadow Root", seed: 13579 },
            Plant { name: "Silver Birch", seed: 24680 },
            Plant { name: "Whispering Willow", seed: 11223 },
            Plant { name: "Sunpetal", seed: 33445 },
            Plant { name: "Moonpetal", seed: 55667 },
            Plant { name: "Starflower", seed: 77889 },
            Plant { name: "Dragon's Breath", seed: 99001 },
            Plant { name: "Ghost Orchid", seed: 10111 },
            Plant { name: "Glimmering Moss", seed: 21212 },
            Plant { name: "Ruby Thorn", seed: 32323 },
            Plant { name: "Sapphire Vine", seed: 43434 },
            Plant { name: "Emerald Ivy", seed: 54545 },
            Plant { name: "Obsidian Rose", seed: 65656 },
            Plant { name: "Opal Cactus", seed: 76767 },
            Plant { name: "Jade Bamboo", seed: 87878 },
            Plant { name: "Topaz Tulip", seed: 98989 },
            Plant { name: "Amethyst Lily", seed: 10101 },
            Plant { name: "Garnet Poppy", seed: 20202 },
            Plant { name: "Diamond Daisy", seed: 30303 },
            Plant { name: "Pearl Blossom", seed: 40404 },
            Plant { name: "Coral Bell", seed: 50505 },
            Plant { name: "Quartz Crystal", seed: 60606 },
            Plant { name: "Turquoise Iris", seed: 70707 },
            Plant { name: "Lapis Lazuli Lupin", seed: 80808 },
            Plant { name: "Malachite Marigold", seed: 90909 },
            Plant { name: "Sunstone Sunflower", seed: 11111 },
            Plant { name: "Moonstone Morning Glory", seed: 22222 },
            Plant { name: "Bloodstone Bellflower", seed: 33333 },
            Plant { name: "Tiger's Eye Thistle", seed: 44444 },
            Plant { name: "Hawk's Eye Heather", seed: 55555 },
            Plant { name: "Cat's Eye Clover", seed: 66666 },
            Plant { name: "Serpentine Snapdragon", seed: 77777 },
            Plant { name: "Agate Aloe", seed: 88888 },
            Plant { name: "Jasper Jasmine", seed: 99999 },
            Plant { name: "Onyx Orchid", seed: 10000 },
            Plant { name: "Carnelian Crocus", seed: 20000 },
            Plant { name: "Sodalite Snowdrop", seed: 30000 },
            Plant { name: "Rhodonite Rhododendron", seed: 40000 },
            Plant { name: "Kyanite Kohlrabi", seed: 50000 },
            Plant { name: "Fluorite Foxglove", seed: 60000 },
            Plant { name: "Aventurine Anemone", seed: 70000 },
            Plant { name: "Amazonite Aster", seed: 80000 },
            Plant { name: "Labradorite Lavender", seed: 90000 },
            Plant { name: "Peridot Petunia", seed: 12121 },
            Plant { name: "Spinel Zinnia", seed: 23232 },
            Plant { name: "Zircon Geranium", seed: 34343 },
            Plant { name: "Tanzanite Dahlia", seed: 45454 },
            Plant { name: "Alexandrite Azalea", seed: 56565 },
            Plant { name: "Morganite Magnolia", seed: 67676 },
            Plant { name: "Heliodor Hibiscus", seed: 78787 },
            Plant { name: "Aquamarine Buttercup", seed: 89898 },
            Plant { name: "Goshenite Gladiolus", seed: 10112 },
            Plant { name: "Bixbite Begonia", seed: 21223 },
            Plant { name: "Fire Opal Freesia", seed: 32334 },
            Plant { name: "Black Opal Oleander", seed: 43445 },
            Plant { name: "Boulder Opal Bluebell", seed: 54556 },
            Plant { name: "Matrix Opal Monkshood", seed: 65667 },
            Plant { name: "Andamooka Opal Aconite", seed: 76778 },
            Plant { name: "Lightning Ridge Opal Larkspur", seed: 87889 },
            Plant { name: "Welsh Opal Wolfsbane", seed: 98990 },
            Plant { name: "Honduran Opal Hollyhock", seed: 10102 },
            Plant { name: "Peruvian Opal Peony", seed: 20203 },
            Plant { name: "Ethiopian Opal Elderflower", seed: 30304 },
            Plant { name: "Mexican Fire Opal Mimosa", seed: 40405 },
            Plant { name: "Brazilian Opal Bougainvillea", seed: 50506 },
            Plant { name: "Slovakian Opal Sweet Pea", seed: 60607 },
            Plant { name: "Tanzanian Opal Tansy", seed: 70708 },
            Plant { name: "Indonesian Opal Impatiens", seed: 80809 },
            Plant { name: "Australian Opal Allium", seed: 90910 },
            Plant { name: "Dragon's Eye", seed: 11112 },
            Plant { name: "Phoenix Feather", seed: 22223 },
            Plant { name: "Griffin's Claw", seed: 33334 },
            Plant { name: "Unicorn's Horn", seed: 44445 },
            Plant { name: "Mermaid's Scale", seed: 55556 },
            Plant { name: "Fairy's Wing", seed: 66667 },
            Plant { name: "Pixie Dust", seed: 77778 },
            Plant { name: "Goblin's Gold", seed: 88889 },
            Plant { name: "Troll's Treasure", seed: 99990 },
            Plant { name: "Dwarf's Delight", seed: 10001 },
            Plant { name: "Elf's Elegance", seed: 20002 },
            Plant { name: "Giant's Growth", seed: 30003 },
            Plant { name: "Nymph's Nectar", seed: 40004 },
            Plant { name: "Satyr's Song", seed: 50005 },
            Plant { name: "Centaur's Courage", seed: 60006 },
            Plant { name: "Minotaur's Maze", seed: 70007 },
            Plant { name: "Hydra's Head", seed: 80008 },
            Plant { name: "Siren's Call", seed: 90009 },
            Plant { name: "Harpy's Feather", seed: 12321 },
            Plant { name: "Chimera's Charm", seed: 23432 },
            Plant { name: "Kraken's Ink", seed: 34543 },
            Plant { name: "Leviathan's Lullaby", seed: 45654 },
            Plant { name: "Behemoth's Blessing", seed: 56765 },
            Plant { name: "Ziz's Zephyr", seed: 67876 },
            Plant { name: "Roc's Roar", seed: 78987 },
            Plant { name: "Thunderbird's Cry", seed: 89098 },
            Plant { name: "Quetzalcoatl's Crest", seed: 90109 },
            Plant { name: "Fenrir's Fang", seed: 10210 },
            Plant { name: "Jormungandr's Coil", seed: 21321 },
            Plant { name: "Sleipnir's Stride", seed: 32432 },
            Plant { name: "Huginn's Thought", seed: 43543 },
            Plant { name: "Muninn's Memory", seed: 54654 },
            Plant { name: "Gungnir's Point", seed: 65765 },
            Plant { name: "Mjolnir's Might", seed: 76876 },
            Plant { name: "Bifrost's Bridge", seed: 87987 },
            Plant { name: "Yggdrasil's Root", seed: 98098 },
            Plant { name: "Asgard's Pride", seed: 10113 },
            Plant { name: "Midgard's Serpent", seed: 21224 },
            Plant { name: "Jotunheim's Jotun", seed: 32335 },
            Plant { name: "Vanaheim's Vanir", seed: 43446 },
            Plant { name: "Alfheim's Elf", seed: 54557 },
            Plant { name: "Svartalfheim's Dwarf", seed: 65668 },
            Plant { name: "Muspelheim's Fire", seed: 76779 },
            Plant { name: "Niflheim's Ice", seed: 87880 },
            Plant { name: "Hel's Hand", seed: 98991 },
            Plant { name: "Ragnarok's Ruin", seed: 10103 },
            Plant { name: "Valhalla's Valor", seed: 20204 },
            Plant { name: "Einherjar's Echo", seed: 30305 },
            Plant { name: "Valkyrie's Voice", seed: 40406 },
            Plant { name: "Norn's Thread", seed: 50507 },
            Plant { name: "Fates' Decree", seed: 60608 },
            Plant { name: "Chaos's Bloom", seed: 70709 },
            Plant { name: "Order's Orchid", seed: 80810 },
            Plant { name: "Light's Lily", seed: 90911 },
            Plant { name: "Dark's Daisy", seed: 11113 },
            Plant { name: "Sun's Sunflower", seed: 22224 },
            Plant { name: "Moon's Morning Glory", seed: 33335 },
            Plant { name: "Star's Snapdragon", seed: 44446 },
            Plant { name: "Sky's Snowdrop", seed: 55557 },
            Plant { name: "Earth's Elderflower", seed: 66668 },
            Plant { name: "Sea's Sweet Pea", seed: 77779 },
            Plant { name: "Fire's Foxglove", seed: 88880 },
            Plant { name: "Wind's Wolfsbane", seed: 99991 },
            Plant { name: "Storm's Snapdragon", seed: 10002 },
            Plant { name: "Ice's Iris", seed: 20003 },
            Plant { name: "Stone's Snapdragon", seed: 30004 },
            Plant { name: "Wood's Wolfsbane", seed: 40005 },
            Plant { name: "Metal's Marigold", seed: 50006 },
            Plant { name: "Void's Violet", seed: 60007 },
            Plant { name: "Aether's Azalea", seed: 70008 },
            Plant { name: "Nether's Nettle", seed: 80009 },
            Plant { name: "Dream's Dahlia", seed: 90010 },
            Plant { name: "Nightmare's Nightshade", seed: 12322 },
            Plant { name: "Memory's Mimosa", seed: 23433 },
            Plant { name: "Thought's Thistle", seed: 34544 },
            Plant { name: "Emotion's Elderflower", seed: 45655 },
            Plant { name: "Soul's Sunflower", seed: 56766 },
            Plant { name: "Spirit's Snapdragon", seed: 67877 },
            Plant { name: "Heart's Hollyhock", seed: 78988 },
            Plant { name: "Mind's Monkshood", seed: 89099 },
            Plant { name: "Body's Bluebell", seed: 90110 },
            Plant { name: "Life's Lily", seed: 10211 },
            Plant { name: "Death's Daisy", seed: 21322 },
            Plant { name: "Time's Thyme", seed: 32433 },
            Plant { name: "Space's Snapdragon", seed: 43544 },
            Plant { name: "Gravity's Gladiolus", seed: 54655 },
            Plant { name: "Energy's Elderflower", seed: 65766 },
            Plant { name: "Matter's Marigold", seed: 76877 },
            Plant { name: "Antimatter's Anemone", seed: 87988 },
            Plant { name: "Quantum's Quince", seed: 98099 },
            Plant { name: "Singularity's Snapdragon", seed: 10114 },
            Plant { name: "Event Horizon's Elderflower", seed: 21225 },
            Plant { name: "Nebula's Nettle", seed: 32336 },
            Plant { name: "Galaxy's Gladiolus", seed: 43447 },
            Plant { name: "Universe's Uva-ursi", seed: 54558 },
            Plant { name: "Multiverse's Monkshood", seed: 65669 },
            Plant { name: "Dimension's Dahlia", seed: 76780 },
            Plant { name: "Reality's Rhododendron", seed: 87881 },
            Plant { name: "Illusion's Iris", seed: 98992 },
            Plant { name: "Truth's Tulip", seed: 10104 },
            Plant { name: "Lie's Lily", seed: 20205 },
            Plant { name: "Hope's Hollyhock", seed: 30306 },
            Plant { name: "Despair's Daisy", seed: 40407 },
            Plant { name: "Joy's Jasmine", seed: 50508 },
            Plant { name: "Sorrow's Snapdragon", seed: 60609 },
            Plant { name: "Love's Lavender", seed: 70710 },
            Plant { name: "Hate's Heather", seed: 80811 },
            Plant { name: "Peace's Peony", seed: 90912 },
            Plant { name: "War's Wolfsbane", seed: 11114 },
            Plant { name: "Wisdom's Wisteria", seed: 22225 },
            Plant { name: "Folly's Foxglove", seed: 33336 },
            Plant { name: "Knowledge's Kohlrabi", seed: 44447 },
            Plant { name: "Ignorance's Iris", seed: 55558 },
            Plant { name: "Power's Poppy", seed: 66669 },
            Plant { name: "Weakness's Wisteria", seed: 77780 },
            Plant { name: "Courage's Crocus", seed: 88881 },
            Plant { name: "Fear's Foxglove", seed: 99992 },
            Plant { name: "Virtue's Violet", seed: 10003 },
            Plant { name: "Sin's Snapdragon", seed: 20004 },
            Plant { name: "Faith's Freesia", seed: 30005 },
            Plant { name: "Doubt's Dahlia", seed: 40006 },
            Plant { name: "Destiny's Daisy", seed: 50007 },
            Plant { name: "Freedom's Foxglove", seed: 60008 },
        ];
        assert!(!plants.is_empty());
    }
}
